services:
  python-gr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-gr
    restart: unless-stopped
    init: true
    ports:
      - "7860:7860"  # Gradio default port, exposed in Dockerfile
